# -*- coding: utf-8 -*-
"""WAEC_Likelihood.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L_x6GlVvyaczcNpD24sWQDNJuLSG589C

WAEC Likelihood Prediction
"""

# import libaries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore', category=FutureWarning)
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.compose import make_column_transformer, ColumnTransformer
from sklearn.pipeline import make_pipeline, Pipeline
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.metrics import mean_squared_error, r2_score, accuracy_score, confusion_matrix, classification_report, roc_curve, roc_auc_score, average_precision_score, PrecisionRecallDisplay, RocCurveDisplay
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.preprocessing import PolynomialFeatures

import joblib

from google.colab import files
uploaded = files.upload()

df = pd.read_csv('waec_pass_likelihood_datasete.csv')
df.head()

# EDA - check for missing values
df.isnull().sum()

# Split Dataset
X = df.drop(columns=['Student_ID', 'WAEC_Pass_Likelihood_Pct', 'Predicted_Outcome'])
y = df['Predicted_Outcome']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from pandas.core.arrays import categorical
# Pipeline Preprocessing
numeric_features = ['Age', 'Study_Hours_Per_Week', 'Attendance_Rate_Pct', 'Previous_Exam_Score_Pct', 'Mock_Exam_Score_Pct', 'Number_of_Subjects', 'Distance_to_School_km']

categorical_features = ['Gender', 'State', 'School_Type', 'Attends_Extra_Classes', 'Parental_Education_Level', 'Household_Income_Level', 'Has_Internet_Access', 'Has_Textbook_Access']

numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features)
    ])

# Model Pipeline
lr_pipeline = Pipeline(steps=[('preprocessor', preprocessor),
                              ('classifier', LogisticRegression(random_state=42))])

rf_pipeline = Pipeline(steps=[('preprocessor', preprocessor),
                              ('classifier', RandomForestClassifier(random_state=42))])

# Train & Evaluation
def evaluate_model(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    y_pred_Proba = model.predict_proba(X_test)[:, 1]

    # Convert y_test to numerical labels for metrics where pos_label is not accepted
    y_test_numeric = y_test.map({'Fail': 0, 'Pass': 1})

    y_pred = (y_pred_Proba >= 0.5).astype(int)

    print('ROC AUC Score:', roc_auc_score(y_test_numeric, y_pred_Proba))
    print('Average Precision Score:', average_precision_score(y_test_numeric, y_pred_Proba))
    print('Accuracy Score:', accuracy_score(y_test_numeric, y_pred))
    print('Confusion Matrix:\n', confusion_matrix(y_test_numeric, y_pred))
    print('Classification Report:\n', classification_report(y_test_numeric, y_pred))

    cm = confusion_matrix(y_test_numeric, y_pred)
    sns.heatmap(cm, annot=True, fmt='d')
    plt.xlabel('Predicted')
    plt.ylabel('Actual')
    plt.show()

    # For RocCurveDisplay and PrecisionRecallDisplay, use original y_test with pos_label
    RocCurveDisplay.from_estimator(model, X_test, y_test, pos_label='Pass')
    plt.show()

    PrecisionRecallDisplay.from_estimator(model, X_test, y_test, pos_label='Pass')
    plt.show()

evaluate_model(lr_pipeline, X_train, X_test, y_train, y_test)

evaluate_model(rf_pipeline, X_train, X_test, y_train, y_test)

# Save model
final_model = lr_pipeline
joblib.dump(final_model, 'final_model.pkl')

# feature importance
# Fit the final_model (Logistic Regression pipeline) to the training data
final_model.fit(X_train, y_train)

preproc = final_model.named_steps['preprocessor']
num_features = numeric_features
cat_features = categorical_features

# Access the fitted one-hot encoder from the preprocessor
cat_encoder = preproc.named_transformers_['cat'].named_steps['onehot']
cat_features_names = cat_encoder.get_feature_names_out(cat_features)

all_features_names = np.concatenate([num_features, cat_features_names])

# Get coefficients from the fitted Logistic Regression classifier
importances = final_model.named_steps['classifier'].coef_[0]

fi = pd.Series(importances, index=all_features_names).sort_values(ascending=False)

plt.figure(figsize=(10, 6))
sns.barplot(x=fi.values, y=fi.index)
plt.xlabel('Importance')
plt.ylabel('Features')
plt.title('Feature Importance (Logistic Regression Coefficients)')
plt.show()

